### ISSUE TITLE
1.4.0 Checklist

### ISSUE THREAD

**Issue by robotconscience** [labatrockwell/openTSPS#81]
1.4.0 will introduce a few new features to simplify OSC-based communication, make maintenance easier, and add more utilities for communication over the Internet. It will also attempt to be self-documenting, introducing tooltips inspired by Ableton Live to provide info about each step in the TSPS process.

GUI overhaul
- [ ] Replace ofxLabGui with ofxUI
- [ ] Add info console for each GUI element
- [ ] Add easily updateable text file for editing GUI docs
- [ ] Add error/log console for debugging

Features + Bug fixes
- [ ] Associate OSC indices with OID (#70) (http://forum.opentsps.com/index.php?topic=15201.0)
- [ ] Further clean up addons (#46)
- [ ] Load/Save background image (#2)
- [ ] Basic Kinect 2 support (libfreenect2 on OS X, ofxKinectV2 on Windows) (#80)

Packaging / downloading
- [ ] Create separate "drivers" download (#75, #63)

Building
- [ ] Remove addons from repo and create cloneaddons.sh

**Comment by emmanuelgeoffray** [comment]
Hi Brett,
I see you've been working on this new version with ofxUI, which is great!

For this new version, may I suggest to remove all addons from repo, and instead use a clone_addons script?
I've seen you are using submodules now, as mentioned in #46 and some addons are candidate to have their own repo.
I am trying to maintain a linux version of openTSPS every 6 month/1 year but it is more and more diffult to keep track of everything as on linux there is no work around to have the addons outside of the of/addons folder.

I've done this [here](https://github.com/emmanuelgeoffray/openTSPS)
But I'm sure I broke things i the Xcode project. I am sorry I can't test it.

But maybe it's quick to rebuild the xcode project with of's projectgenerator now?
Do you use it for openTSPS?

**Comment by robotconscience** [comment]
Hey Emmanuel, that sounds great! Totally on my radar.

I've had to put a pause on TSPS 1.4 as I ramp up teaching a new class this semester... Hoping to pick stuff back up in February! Will keep you posted here.
